import 'package:flutter/material.dart';
import 'package:social_justice_hackathon/home.dart';
import 'package:social_justice_hackathon/polls.dart';
import 'package:social_justice_hackathon/profile.dart';



// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Petitions(),
        ]),
      ),
    );
  }
}

class Petitions extends StatefulWidget {
  @override
  _MyPetitionsState createState() => _MyPetitionsState();
}

class _MyPetitionsState extends State<Petitions>{
   int _currentIndex = 1; // Track the current index of the BottomNavigationBar

  // List of pages for navigation
  final List<Widget> _pages = [
    Home(),
    Petitions(),
    Profile(),
    Polls(),
  ];

  void _onItemTapped(BuildContext context, int index) {
    Widget page;

    // Select the appropriate page based on index
    switch (index) {
      case 0:
        page = Home();
        break;
      case 1:
        page = Petitions();
        break;
      case 2:
        page = Profile();
        break;
      case 3:
        page = Polls();
        break;
      default:
        page = Home();
    }

    // Navigate to the selected page
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => page),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Petitions'),
        backgroundColor: Colors.red,
      ),
      body: SingleChildScrollView(
        child: Column(
      children: [
        Container(
  width: 380,
  height: 831,
  clipBehavior: Clip.antiAlias,
  decoration: BoxDecoration(color: Colors.white),
  child: Stack(
    children: [
      Positioned(
        top: 20,
        left: 10,
        child: Container(
          width: 350,
          height: 138,
          decoration: ShapeDecoration(
            color: Color(0xFFD9D9D9),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        ),
      ),
      Positioned(
        top: 30,
        left: 20,
        child: Container(
          width: 129,
          height: 109,
          decoration: ShapeDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/119x79"),
              fit: BoxFit.fill,
            ),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
          ),
        ),
      ),
      Positioned(
        top: 50,
        left: 200,
        child: SizedBox(
          width: 130,
          child: Text(
            'Exciting adventures await',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w700,
              height: 1.5,
            ),
          ),
        ),
      ),
      Positioned(
        top: 70,
        left: 170,
        child: SizedBox(
          width: 180,
          child: Text(
            'Discover magical kingdoms and brave heroes.',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.black,
              fontSize: 10,
              fontFamily: 'Galdeano',
              fontWeight: FontWeight.w400,
              height: 1.5,
            ),
          ),
        ),
      ),
      Positioned(
              left: 300,
              top: 750,
              child: Container(
                width: 60,
                height: 60,
                decoration: ShapeDecoration(
                  color: Color(0xFFF93636),
                  shape: OvalBorder(),
                ),
                child: ClipOval( // Ensure the image fits within the oval shape
                  child: Container(
                    decoration: BoxDecoration(
                      image: DecorationImage(
                        image: AssetImage("assets/icons/add.png"),
                        fit: BoxFit.contain,
                      ),
                    ),
                  ),
                ),
              ),
            ),
    ],
  ),
)

      ],
    ),
      ),
      
    bottomNavigationBar: BottomNavigationBar(
      items: const <BottomNavigationBarItem>[
      BottomNavigationBarItem(
        icon: Icon(Icons.home),
        label: 'Home',
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.assignment),
        label: 'Petitions',
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.person),
        label: 'Profile',
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.poll),
        label: 'Polls',
      ),
      ],
      currentIndex: 1,
      selectedItemColor: Colors.red,
      unselectedItemColor: const Color.fromARGB(255, 255, 255, 255),
      onTap: (index) {
      // Handle navigation tap
      _onItemTapped(context, index); 
      },
    ),
    );
  }
}