import 'package:flutter/material.dart';
import 'package:social_justice_hackathon/home.dart';
import 'package:social_justice_hackathon/petition.dart';
import 'package:social_justice_hackathon/profile.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Polls(),
        ]),
      ),
    );
  }
}

class Polls extends StatefulWidget {
  @override
  _MypollsState createState() => _MypollsState();
}


class _MypollsState extends State<Polls>{
   int _currentIndex = 0; // Track the current index of the BottomNavigationBar

  // List of pages for navigation
  final List<Widget> _pages = [
    Home(),
    Petitions(),
    Profile(),
    Polls(),
  ];

  void _onItemTapped(BuildContext context, int index) {
    Widget page;

    // Select the appropriate page based on index
    switch (index) {
      case 0:
        page = Home();
        break;
      case 1:
        page = Petitions();
        break;
      case 2:
        page = Profile();
        break;
      case 3:
        page = Polls();
        break;
      default:
        page = Home();
    }

    // Navigate to the selected page
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => page),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Polls'),
        backgroundColor: Colors.red,
      ),
      body: SingleChildScrollView(
        child: Column(
      children: [
        Container(
          width: 380,
          height: 831,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 31,
                top: 20,
                child: Container(
                  width: 284,
                  height: 255,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 56,
                child: SizedBox(
                  width: 285,
                  child: Text(
                    'Should the city increase funding for public parks?',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 11,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 84,
                top: 94,
                child: Text(
                  'Yes',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 11,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 86,
                top: 132,
                child: Text(
                  'No',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 11,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 53,
                top: 80,
                child: Container(
                  width: 20,
                  height: 20,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/20x20"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 53,
                top: 125,
                child: Container(
                  width: 20,
                  height: 20,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/20x20"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
  left: 81,
  top: 170,
  child: Container(
    width: 183,
    height: 39,
    decoration: BoxDecoration(
      color: Color(0xFFF93636),
    ),
    child: Center(
      child: Text(
        'Vote',
        textAlign: TextAlign.center,
        style: TextStyle(
          color: Colors.white,
          fontSize: 14,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
          height: 1.5, // Adjust for spacing if needed
        ),
      ),
    ),
  ),
),
             Positioned(
  left: 53,
  top: 229,
  child: Container(
    width: 242,
    height: 28,
    decoration: BoxDecoration(
      color: Color(0xFFF7F7F7),
    ),
    child: Center(
      child: Text(
        'View Results',
        textAlign: TextAlign.center,
        style: TextStyle(
          color: Colors.black,
          fontSize: 14,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
          height: 1.5, // Adjusted height for better spacing
        ),
      ),
    ),
  ),
),
Positioned(
              left: 300,
              top: 750,
              child: Container(
                width: 60,
                height: 60,
                decoration: ShapeDecoration(
                  color: Color(0xFFF93636),
                  shape: OvalBorder(),
                ),
                child: ClipOval( // Ensure the image fits within the oval shape
                  child: Container(
                    decoration: BoxDecoration(
                      image: DecorationImage(
                        image: AssetImage("assets/icons/add.png"),
                        fit: BoxFit.contain,
                      ),
                    ),
                  ),
                ),
              ),
            ),

              
            ],
          ),
        ),
      ],
    ),
      ),
    bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.assignment),
            label: 'Petitions',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person),
            label: 'Profile',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.poll),
            label: 'Polls',
          ),
        ],
        currentIndex: 3,
        selectedItemColor: Colors.red,
        unselectedItemColor: Colors.grey,
        onTap: (index) {
          // Handle navigation tap
          _onItemTapped(context, index); 
        },
      ),
    );
  }
}
